// src/app/views/accounts/recent-transactions/recent-transactions.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { AccountsService } from '../../../services/accounts.service';
import { Transfer } from '../../../models/transfer.model';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { distinctUntilChanged } from 'rxjs';

@Component({
  selector: 'app-recent-transactions',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './recent-transactions.component.html',
  styleUrl: './recent-transactions.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class RecentTransactionsComponent {
  isLoading = signal(true);
  completedTransfers = signal<Transfer[]>([]);
  noNextPage = signal(false);

  page = signal(1);

  constructor(private readonly accountsService: AccountsService) {
    this.accountsService.completedTransfers$.subscribe((response) => {
      this.completedTransfers.set(response.items);

      if (response.paging_info.total_items <= this.page() * 5) {
        this.noNextPage.set(true);
      } else {
        this.noNextPage.set(false);
      }

      this.isLoading.set(false);
    });

    this.accountsService.account$
      .pipe(takeUntilDestroyed(), distinctUntilChanged())
      .subscribe(() => {
        this.isLoading.set(true);
      });
  }

  nextPage(): void {
    this.isLoading.set(true);
    this.page.update((page) => ++page);
    this.accountsService.setCompletedTransferPage(this.page());
  }

  previousPage(): void {
    this.isLoading.set(true);
    this.page.update((page) => --page);
    this.accountsService.setCompletedTransferPage(this.page());
  }
}

@if (!isLoading()) {
<div>
  <div
    class="grid grid-cols-1 bg-gray-200 border border-gray-300 rounded-t-lg p-2 font-bold"
  >
    Details
  </div>
  @for(transfer of completedTransfers(); track transfer.id) {
  <div
    class="grid grid-cols-2 items-center border border-t-0 border-gray-300 last:rounded-b-lg p-2 hover:bg-slate-100"
    [ngClass]="{
      'line-through text-gray-500': transfer.status === 'declined'
    }"
  >
    <div>
      <div class="text-xs text-gray-500">
        {{ transfer.status | titlecase }} by
        {{ transfer.updated_by?.first_name | titlecase }}
        {{ transfer.updated_by?.last_name | titlecase }}
      </div>
      <div>{{ transfer.description }}</div>
      <div class="text-xs text-gray-500">
        {{ transfer.created_at | date : "MMMM dd, yyyy 'at' h:mma" }}
      </div>
    </div>
    <div class="flex flex-col items-end">
      <div
        class="font-bold"
        [ngClass]="{
          deposit: transfer.amount >= 0 && transfer.status !== 'declined',
          withdraw: transfer.amount < 0 && transfer.status !== 'declined'
        }"
      >
        {{ transfer.amount | currency }}
      </div>
      <div class="text-xs text-gray-500">
        {{ transfer.current_balance | currency }}
      </div>
    </div>
  </div>
  } @empty {
  <div class="border border-t-0 rounded-b-lg p-2 text-gray-500">
    There haven't been any transactions yet for this account.
  </div>
  }
  <div
    *ngIf="completedTransfers().length > 0"
    class="flex justify-between items-center mt-4"
  >
    <button
      class="btn bg-gray-100 border border-gray-300 disabled:cursor-not-allowed px-2 py-1 disabled:opacity-50 hover:bg-gray-200"
      (click)="previousPage()"
      [disabled]="page() <= 1"
    >
      Previous
    </button>
    <button
      class="btn bg-gray-100 border border-gray-300 disabled:cursor-not-allowed px-2 py-1 disabled:opacity-50 hover:bg-gray-200"
      (click)="nextPage()"
      [disabled]="noNextPage()"
    >
      Next
    </button>
  </div>
</div>
} @else {
<div>Loading...</div>
}

// app/(routes)/accounts/[id]/RecentTransactions.tsx
import { formatCurrency, formatDate } from "@/app/utils/formatters";
import {
  fetchCompletedTransactions,
  selectCompletedTransactions,
} from "@/lib/features/accounts/accountsSlice";
import { useAppDispatch, useAppSelector } from "@/lib/hooks";
import { ThunkStatus } from "@/lib/thunk";
import Link from "next/link";
import React from "react";
import { useEffect, useState } from "react";

type RecentTransactionsProps = {
  account: any;
};

export function RecentTransactions({ account }: RecentTransactionsProps) {
  const dispatch = useAppDispatch();
  const { data: transactions, status } = useAppSelector(selectCompletedTransactions);
  const [pageNumber, setPageNumber] = useState(1);
  const itemsPerPage = 8;

  useEffect(() => {
    if (account) {
      dispatch(fetchCompletedTransactions({ account, pageNumber, itemsPerPage }));
    }
  }, [dispatch, account, pageNumber]);

  function goToNextPage(): void {
    setPageNumber((pageNumber) => (pageNumber += 1));
  }

  function goToPreviousPage(): void {
    setPageNumber((pageNumber) => (pageNumber -= 1));
  }

  if (!transactions.items || status === ThunkStatus.Loading) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <div className="text-left">
        <div className="grid grid-cols-2 bg-gray-200 border border-outline rounded-t-[10px] px-3 py-2 font-bold">
          <div>Description</div>
          <div></div>
        </div>
        {transactions.items.length === 0 && (
          <div className="col-span-2 text-left px-3 py-2 bg-white text-gray-500 border border-outline border-t-0 last:rounded-b-[10px]">
            There have been no completed transactions yet.
          </div>
        )}
        {transactions.items.length > 0 &&
          transactions.items.map((transaction: any) => {
            return (
              <div
                key={transaction.id}
                className={`grid grid-cols-2 bg-white px-3 py-2 border border-outline border-t-0 last-of-type:rounded-b-[10px] last:rounded-b-[10px] items-center hover:bg-slate-50 ${
                  transaction.status === "declined" ? "line-through text-gray-400" : ""
                }`}
              >
                <div className="flex flex-col">
                  <div className={`text-gray-500 text-xs`}>
                    <span className="capitalize">{transaction.status}</span> by{" "}
                    <Link
                      href={`/profile/${transaction.updated_by.username}`}
                      className="capitalize"
                    >
                      {transaction.updated_by.first_name} {transaction.updated_by.last_name}
                    </Link>
                  </div>
                  <p>{transaction.description}</p>
                  <time className="text-gray-500 text-xs" dateTime={transaction.created_at}>
                    {formatDate(transaction.created_at, { hour: "numeric", minute: "numeric" })}
                  </time>
                </div>
                <div className="text-right">
                  <p
                    className={`font-bold ${
                      transaction.status === "declined"
                        ? "text-gray-400"
                        : transaction.amount < 0
                        ? "text-pink-600"
                        : "text-emerald-700"
                    }`}
                  >
                    {formatCurrency(transaction.amount)}
                  </p>
                  <p className="text-gray-500 text-xs">
                    {formatCurrency(transaction.current_balance)}
                  </p>
                </div>
              </div>
            );
          })}
      </div>
      <div className="flex justify-between">
        <button onClick={goToPreviousPage} className="common outlined" disabled={pageNumber === 1}>
          Previous
        </button>
        <button
          onClick={goToNextPage}
          className="common outlined"
          disabled={pageNumber * itemsPerPage >= transactions.total_items}
        >
          Next
        </button>
      </div>
    </>
  );
}
